services:
  postgres_mcdonalds:
    image: postgres:14.5
    environment:
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "senha"
      PORT : "5432"
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgres
      - ./sql/mcdonalds_health_db.sql:/docker-entrypoint-initdb.d/A_mcdonalds_health_db.sql
      - ./sql/alter_table_types_every_numerical_type_column.sql:/docker-entrypoint-initdb.d/B_alter_table.sql
      - ./sql/ddl/creating_entities.sql:/docker-entrypoint-initdb.d/C_creating_entities.sql
      - ./sql/dml/insert_values_company.sql:/docker-entrypoint-initdb.d/D_insert_company.sql
      - ./sql/dml/insert_values_snack.sql:/docker-entrypoint-initdb.d/E_insert_snack.sql
      - ./sql/dml/insert_values_nutritional_info.sql:/docker-entrypoint-initdb.d/F_insert_values_nutritional_info.sql
      - ./sql/normalize_tables/normalize_tables.sql:/docker-entrypoint-initdb.d/G_normalize_tables.sql
      - ./sql/apply_index/index.sql:/docker-entrypoint-initdb.d/H_apply_index.sql
volumes:
  postgres_volume: